CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(255) NOT NULL,
                                     email VARCHAR(512) NOT NULL,
                                     CONSTRAINT pk_user PRIMARY KEY (id),
                                     CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(255) NOT NULL,
                                     description VARCHAR(512) NOT NULL,
                                     available BOOLEAN NOT NULL,
                                     owner_id BIGINT NOT NULL REFERENCES users(id),
                                     CONSTRAINT pk_item PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bookings (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     item_id BIGINT NOT NULL REFERENCES items(id),
                                     booker BIGINT NOT NULL REFERENCES users(id),
                                     status BIGINT NOT NULL,
                                     start DATE NOT NULL,
                                     end DATE NOT NULL,
                                     CONSTRAINT pk_booking PRIMARY KEY (id)
);